version: "3.9"

services:
  # Firebase Emulator for local Firestore
  firebase-emulator:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:474.0.0-emulators
    command: >
      gcloud beta emulators firestore start --host-port=0.0.0.0:8080
    ports:
      - "8088:8080"
    healthcheck:
      test: ["CMD", "bash", "-lc", "nc -z localhost 8080"]
      interval: 5s
      timeout: 2s
      retries: 20

  # Focus Service - Activities
  focus-service:
    build:
      context: .
      dockerfile: focus-service/Dockerfile
    environment:
      PORT: "8080"
      AUTH_MODE: "noop"
      DATASTORE: "firestore"
      GCP_PROJECT_ID: "focusnest-dev"
      FIRESTORE_EMULATOR_HOST: "firebase-emulator:8080"
    depends_on:
      firebase-emulator:
        condition: service_healthy
    ports:
      - "8081:8080"

  # Chatbot Service - LLM/chat
  chatbot-service:
    build:
      context: .
      dockerfile: chatbot-service/Dockerfile
    environment:
      PORT: "8080"
      GCP_PROJECT_ID: "focusnest-dev"
      FIRESTORE_EMULATOR_HOST: "firebase-emulator:8080"
    depends_on:
      firebase-emulator:
        condition: service_healthy
    ports:
      - "8082:8080"

  # Progress Service - Analytics
  progress-service:
    build:
      context: .
      dockerfile: progress-service/Dockerfile
    environment:
      PORT: "8080"
      GCP_PROJECT_ID: "focusnest-dev"
      FIRESTORE_EMULATOR_HOST: "firebase-emulator:8080"
    depends_on:
      firebase-emulator:
        condition: service_healthy
    ports:
      - "8083:8080"

  # User Service
  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    environment:
      PORT: "8080"
      GCP_PROJECT_ID: "focusnest-dev"
      FIRESTORE_EMULATOR_HOST: "firebase-emulator:8080"
    depends_on:
      firebase-emulator:
        condition: service_healthy
    ports:
      - "8084:8080"

  # Gateway API - public entry & routing
  gateway-api:
    build:
      context: .
      dockerfile: gateway-api/Dockerfile
    environment:
      PORT: "8080"
      # Clerk (put these in your .env for dev)
      CLERK_JWKS_URL: "${CLERK_JWKS_URL}"
      CLERK_AUDIENCE: "${CLERK_AUDIENCE}"
      CLERK_ISSUER: "${CLERK_ISSUER}"
      # Internal service URLs
      ACTIVITY_URL: "http://focus-service:8080"
      USER_URL: "http://user-service:8080"
      ANALYTICS_URL: "http://progress-service:8080"
      CHATBOT_URL: "http://chatbot-service:8080"
    depends_on:
      - focus-service
      - chatbot-service
      - progress-service
      - user-service
    ports:
      - "8080:8080"
