services:
  # Gateway API - Main entry point with authentication and routing
  gateway-api:
    build:
      context: .
      dockerfile: gateway-api/Dockerfile
    environment:
      PORT: "8080"
      CLERK_JWKS_URL: "${CLERK_JWKS_URL}"
      CLERK_AUDIENCE: "${CLERK_AUDIENCE}"
      CLERK_ISSUER: "${CLERK_ISSUER}"
      ACTIVITY_URL: "http://activity-service:8080"
      USER_URL: "http://user-service:8080"
      SESSION_URL: "http://session-service:8080"
      MEDIA_URL: "http://media-service:8080"
      ANALYTICS_URL: "http://analytics-service:8080"
      WEBHOOK_URL: "http://webhook-service:8080"
    ports:
      - "8080:8080"
    depends_on:
      - activity-service
      - user-service
      - session-service
      - media-service
      - analytics-service
      - webhook-service


  # Activity Service - Enhanced with productivity, chatbot, analytics, and user features
  activity-service:
    build:
      context: .
      dockerfile: activity-service/Dockerfile
    environment:
      PORT: "8080"
      AUTH_MODE: "noop"  # Use noop for development, set to "clerk" for production
      DATASTORE: "firestore"  # Use firestore for NoSQL data
      GCP_PROJECT_ID: "focusnest-dev"
      FIRESTORE_EMULATOR_HOST: "firebase-emulator:8080"
    ports:
      - "8081:8080"
    depends_on:
      - firebase-emulator

  # User Service
  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    environment:
      PORT: "8080"
      GCP_PROJECT_ID: "focusnest-dev"
      FIRESTORE_EMULATOR_HOST: "firebase-emulator:8080"
    ports:
      - "8082:8080"
    depends_on:
      - firebase-emulator

  # Session Service
  session-service:
    build:
      context: .
      dockerfile: session-service/Dockerfile
    environment:
      PORT: "8080"
      GCP_PROJECT_ID: "focusnest-dev"
      FIRESTORE_EMULATOR_HOST: "firebase-emulator:8080"
    ports:
      - "8083:8080"
    depends_on:
      - firebase-emulator

  # Media Service
  media-service:
    build:
      context: .
      dockerfile: media-service/Dockerfile
    environment:
      PORT: "8080"
      GCP_PROJECT_ID: "focusnest-dev"
      FIRESTORE_EMULATOR_HOST: "firebase-emulator:8080"
    ports:
      - "8084:8080"
    depends_on:
      - firebase-emulator

  # Analytics Service
  analytics-service:
    build:
      context: .
      dockerfile: analytics-service/Dockerfile
    environment:
      PORT: "8080"
      GCP_PROJECT_ID: "focusnest-dev"
      FIRESTORE_EMULATOR_HOST: "firebase-emulator:8080"
    ports:
      - "8085:8080"
    depends_on:
      - firebase-emulator

  # Webhook Service
  webhook-service:
    build:
      context: .
      dockerfile: webhook-service/Dockerfile
    environment:
      PORT: "8080"
      GCP_PROJECT_ID: "focusnest-dev"
      FIRESTORE_EMULATOR_HOST: "firebase-emulator:8080"
    ports:
      - "8086:8080"
    depends_on:
      - firebase-emulator

  # Firebase Emulator for local development
  firebase-emulator:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:474.0.0-emulators
    command: >-
      gcloud beta emulators firestore start --host-port=0.0.0.0:8080
    ports:
      - "8088:8080"
