version: "3.10"

services:
  gateway:
    build:
      context: .
      dockerfile: gateway-api/Dockerfile
    environment:
      PORT: "8080"
      GCP_PROJECT_ID: "focusnest-dev"
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - firebase-emulator

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    environment:
      PORT: "8081"
      GCP_PROJECT_ID: "focusnest-dev"
      FIRESTORE_EMULATOR_HOST: "firebase-emulator:8080"
    ports:
      - "8081:8081"
    depends_on:
      - firebase-emulator

  firebase-emulator:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:474.0.0-emulators
    command: >-
      gcloud beta emulators firestore start --host-port=0.0.0.0:8080
    ports:
      - "8088:8080"
