openapi: 3.1.0
info:
  title: FocusNest Activity Service
  version: 0.0.1
paths:
  /healthz:
    get:
      operationId: getHealth
      responses:
        "200":
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
  /v1/activities:
    get:
      operationId: listActivities
      responses:
        "200":
          description: A list of activities
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Activity"
components:
  schemas:
    HealthResponse:
      type: object
      properties:
        status:
          type: string
        service:
          type: string
        version:
          type: string
    Activity:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        durationMinutes:
          type: integer
