openapi: 3.1.0
info:
  title: FocusNest Notification Service
  version: 0.0.1
paths:
  /healthz:
    get:
      operationId: getHealth
      responses:
        "200":
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
  /v1/notify/test:
    post:
      operationId: sendTestNotification
      responses:
        "204":
          description: Notification triggered
components:
  schemas:
    HealthResponse:
      type: object
      properties:
        status:
          type: string
        service:
          type: string
        version:
          type: string
