openapi: 3.1.0
info:
  title: FocusNest Auth Gateway API
  version: 0.0.1
paths:
  /healthz:
    get:
      summary: Readiness probe
      responses:
        "200":
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
components:
  schemas:
    HealthResponse:
      type: object
      properties:
        status:
          type: string
        service:
          type: string
        version:
          type: string
