openapi: 3.1.0
info:
  title: FocusNest API
  version: 0.1.0
  description: FocusNest microservices API - Productivity tracking and analytics
servers:
  - url: https://gateway-api-855213286667.asia-southeast2.run.app
    description: Production
  - url: http://localhost:8080
    description: Local development
paths:
  # Progress Service - Streaks
  /v1/streaks/month:
    get:
      operationId: getMonthlyStreak
      summary: Get monthly streak data
      tags:
        - streaks
      security:
        - bearerAuth: []
      parameters:
        - name: month
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 12
          description: Month (1-12), defaults to current month
        - name: year
          in: query
          required: false
          schema:
            type: integer
            minimum: 2020
            maximum: 2030
          description: Year, defaults to current year
      responses:
        "200":
          description: Monthly streak data retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MonthlyStreakData"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /v1/streaks/week:
    get:
      operationId: getWeeklyStreak
      summary: Get weekly streak data
      tags:
        - streaks
      security:
        - bearerAuth: []
      parameters:
        - name: date
          in: query
          required: false
          schema:
            type: string
            format: date
          description: Date to get week for (YYYY-MM-DD), defaults to current week
      responses:
        "200":
          description: Weekly streak data retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WeeklyStreakData"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  
  # Focus Service - Productivities
  /v1/productivities:
    get:
      operationId: listProductivities
      summary: List productivity entries for the authenticated user (paginated)
      tags:
        - productivities
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: page
          description: 1-based page number. Defaults to 1.
          schema:
            type: integer
            minimum: 1
        - in: query
          name: pageSize
          description: Page size (max 100). Defaults to 20.
          schema:
            type: integer
            minimum: 1
            maximum: 100
        - in: query
          name: startDate
          description: Start date for filtering (YYYY-MM-DD)
          schema:
            type: string
            format: date
        - in: query
          name: endDate
          description: End date for filtering (YYYY-MM-DD)
          schema:
            type: string
            format: date
      responses:
        "200":
          description: Paginated list of productivity entries
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductivityListResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Missing or invalid authentication token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    post:
      operationId: createProductivity
      summary: Create a new productivity entry
      tags:
        - productivities
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                category:
                  type: string
                  description: Category of the productivity entry
                time_mode:
                  type: string
                  description: Time mode (e.g., Pomodoro, Focus, etc.)
                description:
                  type: string
                  description: Description of the activity
                mood:
                  type: string
                  description: Mood during the activity
                cycles:
                  type: integer
                  description: Number of cycles completed
                elapsed_ms:
                  type: integer
                  description: Elapsed time in milliseconds
                start_at:
                  type: string
                  format: date-time
                  description: Start time of the activity
                end_at:
                  type: string
                  format: date-time
                  description: End time of the activity
                image:
                  type: string
                  format: binary
                  description: Optional image file
      responses:
        "201":
          description: Productivity entry created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductivityEntry"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Missing or invalid authentication token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /v1/productivities/{id}:
    get:
      operationId: getProductivity
      summary: Get a specific productivity entry by ID
      tags:
        - productivities
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Productivity entry ID
      responses:
        "200":
          description: Productivity entry retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductivityEntry"
        "404":
          description: Productivity entry not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Missing or invalid authentication token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    delete:
      operationId: deleteProductivity
      summary: Delete a productivity entry by ID
      tags:
        - productivities
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Productivity entry ID
      responses:
        "204":
          description: Productivity entry deleted successfully
        "404":
          description: Productivity entry not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Missing or invalid authentication token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        requestId:
          type: string
      required:
        - code
        - message
    MonthlyStreakData:
      type: object
      properties:
        month:
          type: integer
          minimum: 1
          maximum: 12
        year:
          type: integer
        total_streak:
          type: integer
          description: Longest consecutive active days in the month
        current_streak:
          type: integer
          description: Current running streak
        days:
          type: array
          items:
            $ref: "#/components/schemas/DayStatus"
      required:
        - month
        - year
        - total_streak
        - current_streak
        - days
    WeeklyStreakData:
      type: object
      properties:
        week:
          type: string
          description: Week in YYYY-WW format
        total_streak:
          type: integer
          description: Longest consecutive active days in the week
        current_streak:
          type: integer
          description: Current running streak
        days:
          type: array
          items:
            $ref: "#/components/schemas/DayStatus"
      required:
        - week
        - total_streak
        - current_streak
        - days
    DayStatus:
      type: object
      properties:
        date:
          type: string
          format: date
          description: Date in YYYY-MM-DD format
        day:
          type: string
          description: Day of the week (Monday, Tuesday, etc.)
        status:
          type: string
          enum: [active, skipped, upcoming]
          description: Status of the day
      required:
        - date
        - day
        - status
    ProductivityEntry:
      type: object
      properties:
        id:
          type: string
        user_id:
          type: string
        category:
          type: string
        time_mode:
          type: string
        description:
          type: string
        mood:
          type: string
        cycles:
          type: integer
        elapsed_ms:
          type: integer
        start_at:
          type: string
          format: date-time
        end_at:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        image:
          $ref: "#/components/schemas/ImageInfo"
      required:
        - id
        - user_id
        - category
        - time_mode
        - elapsed_ms
        - start_at
        - end_at
        - created_at
        - updated_at
    ProductivityListResponse:
      type: object
      properties:
        entries:
          type: array
          items:
            $ref: "#/components/schemas/ProductivityEntry"
        page_info:
          $ref: "#/components/schemas/PageInfo"
      required:
        - entries
        - page_info
    PageInfo:
      type: object
      properties:
        page:
          type: integer
        page_size:
          type: integer
        total_pages:
          type: integer
        has_next:
          type: boolean
        has_previous:
          type: boolean
        next_token:
          type: string
      required:
        - page
        - page_size
        - has_next
        - has_previous
    ImageInfo:
      type: object
      properties:
        original_url:
          type: string
        overview_url:
          type: string
      required:
        - original_url
        - overview_url