openapi: 3.1.0
info:
  title: FocusNest Session Service
  version: 0.0.1
paths:
  /healthz:
    get:
      operationId: getHealth
      responses:
        "200":
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
  /v1/sessions:
    get:
      operationId: listSessions
      parameters:
        - in: query
          name: status
          schema:
            type: string
      responses:
        "200":
          description: A list of sessions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Session"
components:
  schemas:
    HealthResponse:
      type: object
      properties:
        status:
          type: string
        service:
          type: string
        version:
          type: string
    Session:
      type: object
      properties:
        id:
          type: string
        status:
          type: string
        durationSeconds:
          type: integer
