openapi: 3.1.0
info:
  title: FocusNest User Service
  version: 0.0.1
paths:
  /healthz:
    get:
      operationId: getHealth
      responses:
        "200":
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
  /v1/me:
    get:
      operationId: getMe
      responses:
        "200":
          description: Current user profile
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserProfile"
components:
  schemas:
    HealthResponse:
      type: object
      properties:
        status:
          type: string
        service:
          type: string
        version:
          type: string
    UserProfile:
      type: object
      properties:
        userId:
          type: string
        email:
          type: string
        displayName:
          type: string
