openapi: 3.1.0
info:
  title: FocusNest Analytics Service
  version: 0.0.1
paths:
  /healthz:
    get:
      operationId: getHealth
      responses:
        "200":
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
  /v1/analytics/me/daily:
    get:
      operationId: getDailyAnalytics
      parameters:
        - in: query
          name: from
          schema:
            type: string
            format: date
        - in: query
          name: to
          schema:
            type: string
            format: date
      responses:
        "200":
          description: Daily analytics summary
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DailyAnalyticsResponse"
components:
  schemas:
    HealthResponse:
      type: object
      properties:
        status:
          type: string
        service:
          type: string
        version:
          type: string
    DailyAnalyticsResponse:
      type: object
      properties:
        days:
          type: array
          items:
            type: object
            properties:
              date:
                type: string
                format: date
              totalDurationSeconds:
                type: integer
