openapi: 3.1.0
info:
  title: FocusNest Progress Service
  version: 0.1.0
  description: Progress analytics service with daily summaries and aggregations
servers:
  - url: https://gateway-api-855213286667.asia-southeast2.run.app
    description: Production
  - url: http://localhost:8080
    description: Local development
paths:
  /v1/streaks/month:
    get:
      operationId: getMonthlyStreak
      summary: Get monthly streak data
      tags:
        - streaks
      security:
        - bearerAuth: []
      parameters:
        - name: month
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 12
          description: Month (1-12), defaults to current month
        - name: year
          in: query
          required: false
          schema:
            type: integer
            minimum: 2020
            maximum: 2030
          description: Year, defaults to current year
      responses:
        "200":
          description: Monthly streak data retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MonthlyStreakData"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /v1/streaks/week:
    get:
      operationId: getWeeklyStreak
      summary: Get weekly streak data
      tags:
        - streaks
      security:
        - bearerAuth: []
      parameters:
        - name: date
          in: query
          required: false
          schema:
            type: string
            format: date
          description: Date to get week for (YYYY-MM-DD), defaults to current week
      responses:
        "200":
          description: Weekly streak data retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WeeklyStreakData"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        requestId:
          type: string
      required:
        - code
        - message
    MonthlyStreakData:
      type: object
      properties:
        month:
          type: integer
          minimum: 1
          maximum: 12
        year:
          type: integer
        total_streak:
          type: integer
          description: Longest consecutive active days in the month
        current_streak:
          type: integer
          description: Current running streak
        days:
          type: array
          items:
            $ref: "#/components/schemas/DayStatus"
      required:
        - month
        - year
        - total_streak
        - current_streak
        - days
    WeeklyStreakData:
      type: object
      properties:
        week:
          type: string
          description: Week in YYYY-WW format
        total_streak:
          type: integer
          description: Longest consecutive active days in the week
        current_streak:
          type: integer
          description: Current running streak
        days:
          type: array
          items:
            $ref: "#/components/schemas/DayStatus"
      required:
        - week
        - total_streak
        - current_streak
        - days
    DayStatus:
      type: object
      properties:
        date:
          type: string
          format: date
          description: Date in YYYY-MM-DD format
        day:
          type: string
          description: Day of the week (Monday, Tuesday, etc.)
        status:
          type: string
          enum: [active, skipped, upcoming]
          description: Status of the day
      required:
        - date
        - day
        - status