openapi: 3.1.0
info:
  title: FocusNest Webhook Service
  version: 0.0.1
paths:
  /healthz:
    get:
      operationId: getHealth
      responses:
        "200":
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
  /v1/webhooks/clerk:
    post:
      operationId: handleClerkWebhook
      responses:
        "202":
          description: Webhook accepted
components:
  schemas:
    HealthResponse:
      type: object
      properties:
        status:
          type: string
        service:
          type: string
        version:
          type: string
