name: Deploy Gateway API

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'gateway-api/**'
      - 'shared-libs/**'
      - '.github/workflows/deploy-gateway.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    env:
      SERVICE_NAME: gateway-api
      REGION: ${{ vars.GCP_REGION }}
      PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
      IMAGE: ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/focusnest/gateway-api:latest

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Artifact Registry Docker auth
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build image
        run: |
          docker build -t $IMAGE -f gateway-api/Dockerfile .

      - name: Push image
        run: docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE \
            --platform managed \
            --region $REGION \
            --allow-unauthenticated \
            --port 8080 \
            --set-env-vars "AUTH_MODE=clerk,ACTIVITY_SERVICE_URL=${{ vars.ACTIVITY_SERVICE_URL }},USER_SERVICE_URL=${{ vars.USER_SERVICE_URL }},SESSION_SERVICE_URL=${{ vars.SESSION_SERVICE_URL }},MEDIA_SERVICE_URL=${{ vars.MEDIA_SERVICE_URL }},ANALYTICS_SERVICE_URL=${{ vars.ANALYTICS_SERVICE_URL }},WEBHOOK_SERVICE_URL=${{ vars.WEBHOOK_SERVICE_URL }},CLERK_JWKS_URL=${{ secrets.CLERK_JWKS_URL }},CLERK_AUDIENCE=${{ secrets.CLERK_AUDIENCE }},CLERK_ISSUER=${{ secrets.CLERK_ISSUER }}"


