name: Deploy Gateway API

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'gateway-api/**'
      - 'shared-libs/**'
      - '.github/workflows/gateway-api.yml'

env:
  PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  REGION: ${{ vars.GCP_REGION }}
  SERVICE_NAME: gateway-api

jobs:
  deploy-gateway:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Get backend service URLs
        id: get_urls
        run: |
          ACTIVITY_URL=$(gcloud run services describe activity-service --platform managed --region $REGION --format 'value(status.url)' 2>/dev/null || echo "")
          USER_URL=$(gcloud run services describe user-service --platform managed --region $REGION --format 'value(status.url)' 2>/dev/null || echo "https://placeholder")
          SESSION_URL=$(gcloud run services describe session-service --platform managed --region $REGION --format 'value(status.url)' 2>/dev/null || echo "https://placeholder")
          echo "activity_url=$ACTIVITY_URL" >> $GITHUB_OUTPUT
          echo "user_url=$USER_URL" >> $GITHUB_OUTPUT
          echo "session_url=$SESSION_URL" >> $GITHUB_OUTPUT
      
      - name: Build Docker image
        run: |
          gcloud builds submit \
            --timeout=10m \
            --suppress-logs \
            --config=gateway-api/cloudbuild.yaml
      
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image gcr.io/$PROJECT_ID/$SERVICE_NAME \
            --platform managed \
            --region $REGION \
            --allow-unauthenticated \
            --ingress all \
            --port 8080 \
            --memory 512Mi \
            --max-instances 10 \
            --min-instances 0 \
            --timeout 60s \
            --set-env-vars="GCP_PROJECT_ID=$PROJECT_ID" \
            --set-env-vars="AUTH_MODE=clerk" \
            --set-env-vars="CLERK_JWKS_URL=${{ secrets.CLERK_JWKS_URL }}" \
            --set-env-vars="CLERK_ISSUER=${{ secrets.CLERK_ISSUER }}" \
            --set-env-vars="ACTIVITY_URL=${{ steps.get_urls.outputs.activity_url }}" \
            --set-env-vars="USER_URL=${{ steps.get_urls.outputs.user_url }}" \
            --set-env-vars="SESSION_URL=${{ steps.get_urls.outputs.session_url }}" \
            --set-env-vars="MEDIA_URL=https://placeholder" \
            --set-env-vars="ANALYTICS_URL=https://placeholder" \
            --set-env-vars="WEBHOOK_URL=https://placeholder"
      
      - name: Get Service URL
        id: url
        run: |
          URL=$(gcloud run services describe $SERVICE_NAME \
            --platform managed \
            --region $REGION \
            --format 'value(status.url)')
          echo "Gateway deployed to: $URL"
          echo "url=$URL" >> $GITHUB_OUTPUT
      
      - name: Summary
        run: |
          echo "## Gateway Deployment Successful" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Service:** $SERVICE_NAME" >> $GITHUB_STEP_SUMMARY
          echo "**URL:** ${{ steps.url.outputs.url }}" >> $GITHUB_STEP_SUMMARY
          echo "**Region:** $REGION" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Backend Services" >> $GITHUB_STEP_SUMMARY
          echo "- Activity: ${{ steps.get_urls.outputs.activity_url }}" >> $GITHUB_STEP_SUMMARY
          echo "- User: ${{ steps.get_urls.outputs.user_url }}" >> $GITHUB_STEP_SUMMARY
          echo "- Session: ${{ steps.get_urls.outputs.session_url }}" >> $GITHUB_STEP_SUMMARY
